language: node_js
services:
  - postgresql

addons:
  postgresql: "14.3 "

sudo: true

before_script:
  - sudo apt-get install postgresql-14.3-postgis-3.1 postgis -y -q
  - psql -c 'create database my_database;' -U postgres  
  - psql -c 'BEGIN; GRANT ALL PRIVILEGES ON DATABASE my_database TO postgres; CREATE EXTENSION IF NOT EXISTS postgis; COMMIT;' -U postgres  


node_js:
  - 16

# install dependencies
install:
  - npm install
  - npm install dotenv

# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always