language: node_js
services:
  - postgresql

addons:
  postgresql: "14.3"
  apt:
    packages:
    - postgresql-14.3-postgis-3.2.1

sudo: true

before_script:
  - psql -c 'create database my_database;' -U postgres  
  - psql -c 'BEGIN; GRANT ALL PRIVILEGES ON DATABASE my_database TO postgres; CREATE EXTENSION IF NOT EXISTS postgis; COMMIT;' -U postgres  


node_js:
  - 16

# install dependencies
install:
  - npm install
  - npm install dotenv

# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always