language: node_js
services:
  - postgresql

dist: trusty
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

sudo: true

before_script:
#  - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
#  - psql -U postgres -c 'begin; create extension if not exists postgis schema public; commit;'
  - psql -c 'create database my_database;' -U postgres
  
node_js:
  - 16

# install dependencies
install:
  - npm install
  - npm install dotenv

# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always