language: node_js
services:
  - postgresql

addons:
  postgresql: "9.5"

node_js:
  - 16
# install dependencies
install:
  - npm install
  - npm install dotenv


before_script:
  - psql -c 'create database my_database;' -U postgres  
  - psql -c 'BEGIN; GRANT ALL PRIVILEGES ON DATABASE my_database TO postgres; CREATE EXTENSION IF NOT EXISTS postgis; COMMIT;' -U postgres  

# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always