language: node_js
services:
  - docker

#before_install:
#  - docker pull bitnami/postgresql
#  - docker run bitnami/postgresql /bin/sh -c "BEGIN; GRANT ALL PRIVILEGES ON DATABASE my_database TO my_user; CREATE EXTENSION IF NOT EXISTS postgis; COMMIT;"
#  - docker run -e POSTGRESQL_USERNAME=postgres -e POSTGRESQL_DATABASE=my_database -e POSTGRESQL_PASSWORD=pass -p 5432:5432 bitnami/postgresql

install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart

node_js:
  - 16

# install dependencies
install:
  - npm install
  - npm install dotenv

# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always