language: node_js
addons:
  apt:
    packages:
      - postgresql-11
      - postgresql-11-postgis-2.5
      - postgresql-11-postgis-2.5-scripts
  postgresql: '11'

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11

services:
  - postgresql

env:
  global:
    - PGPORT=5433
    
node_js:
  - 16
# install dependencies
install:
  - npm install
  - npm install dotenv


# run tests
script:
  - npm test
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always