version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db