version: "3"

services:
  db:
    container_name: db
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    command: "dockerize -wait ${DATABASE_URL} /bin/bash entrypoint.sh"